### ISSUE TITLE
Funktion zum Export als GPX

### ISSUE THREAD

**Issue by skaramuz** [Cyclenerd/veloherodown#1]
Hi,
vielen Dank für das Tool - habe ich lange gesucht, neulich selbst zusammengepfuscht, aber deine Version gefällt mir viel besser :) Eine Funktion zum Download als GPX könntest du noch einbauen:

`function export_activity_gpx() {
        curl "https://app.velohero.com/export/activity/gpx/$1" -F sso="$VELOHERO_SSO_KEY" -o "$VELOHERO_EXPORT_DIR/$1.gpx" --fail -A "$MY_USERAGENT" --compressed
}`

Viele Grüße und Dank!

**Comment by Cyclenerd** [comment]
Hi,

jo das würde gehen. Es gibt auch einen TCX, CSV und KML Export. PWX hat aber die Runden und kann z.B. von Golden Cheetah gelesen werden. Im JSON sind alle Details.

Viele Grüße
Nils
