### ISSUE TITLE
Enhancement: Check for availability of curl

### ISSUE THREAD

**Issue by gjaekel** [Cyclenerd/veloherodown#2]
The common Unix tool `curl` is used to handle HTML communication. If it's not availiable (or in path), the user gets a wrong hint:

```
gjaekel@jelly:~$ veloherodown 

Please specify in the file '/home/gjaekel/.veloherorc' the location for the export.

----- snip -------------------------------------------------------------

VELOHERO_EXPORT_DIR=[specify location for export]

----- snap -------------------------------------------------------------

Important: Do not use spaces!
```

Please add a check and an appropriate error message.

**Comment by Cyclenerd** [comment]
Fixed with https://github.com/Cyclenerd/veloherodown/commit/123d263cca7b331b5c1544203c0f194d6007f80a
