### ISSUE TITLE
Feature Request: Allow to specify export format(s)

### ISSUE THREAD

**Issue by gjaekel** [Cyclenerd/veloherodown#6]
The tools is able to download workouts from the server in several formats. At the moment, the actual format(s) of the exported data (JSON, PWX) are hard coded.

Please allow the user to choice the format of exported data.

Proposal: Specify the format(s) to export as a list of command arguments, i.e.

    velohero [format]...

with `format` choosen from `json`, `pwx`, `csv`, `gpx`, `klm`, `tcx`. Default might be `json`.

**Comment by gjaekel** [comment]
_I'm going to provide a pull request to implement this feature_

**Comment by Cyclenerd** [comment]
Done with https://github.com/Cyclenerd/veloherodown/commit/4f2150cb8b5c56dee9ca457d1e328bfb7508bf48
